# Generated by Django 4.2.1 on 2023-05-24 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coworking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rooms',
            name='created',
        ),
        migrations.RemoveField(
            model_name='rooms',
            name='updated',
        ),
    ]
